---
title: "EP Tests"
author: "Swupnil Sahai"
date: "October 6, 2015"
output: pdf_document
---

\section{1. Uknown Mean}
\subsection{Formulation}
We start by fitting one of the simplest possible models that isn't hierarchical in nature:
$$ x_i \sim N(\phi, 1) $$

Generating 1000 data points with $\phi = 200$, we give EP and HMC the following prior:
$$\phi \sim N(0, 20)$$

\subsection{Results}
EP and HMC converge to similar posteriors of $\phi$, with the values stabilizing immidiatedly after the first iteration.

\begin{table}[ht]
\caption{Posterior of $\phi$ (K = 5)}
\centering
\begin{tabular}{c c c c c c c}
\hline
Parameter & True & Prior & HMC & EP Iter 1 & EP Iter 2 & EP Iter 3\\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi)$ & 200 & 0 & 200.0165 & 200.0181 & 200.015 & 200.0199\\
$Var(\phi)$ & -- & 20 & 0.01214 & 0.01433 & 0.01243 & 0.01314\\
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

\pagebreak
\section{2. Uknown Means ( + Hierarchical Mean)}
\subsection{Formulation}
We then try a slightly more interesting model with local unknown means drawn from a global uknown mean and known variance:
$$ \theta_j \sim N(\phi, 10)$$
$$ x_{ij} \sim N(\theta_j, 1) $$

Generating 50 $\theta_j$'s from $\phi = 200$, and then sampling 1000 data points from each group $j$, we give EP and HMC the following prior:
$$\phi \sim N(0, 20)$$

\subsection{Results}
EP and HMC converge to same posterior of $\phi$, regardless of the number of sites.

\begin{table}[ht]
\caption{Posterior of $\phi$}
\centering
\begin{tabular}{c c c c c c c}
\hline
Parameter & True & Prior & HMC & EP K=5 & EP K=10 & EP K=25 \\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi_1)$ & 200 & 0 & 200.07 & 200.23 & 200.24 & 200.11\\
$Var(\phi_1)$ & -- & 20 & 2.03 & 2.08 & 1.99 & 1.99\\ \hline
Time (Serial) & -- & -- & 201 s & 81 s & 73 s & 69 s\\ 
Time (Parallel) & -- & -- & 201 s & 16.2 s & 7.3 s & 2.8 s\\ 
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

Additionally, as in the non-hierarchical case, we find that the posterior stabilizes after the first iteration, regardless of the number of sites.

\begin{table}[ht]
\caption{Posterior of $\phi$ (K = 10)}
\centering
\begin{tabular}{c c c c c c c}
\hline
Parameter & True & Prior & HMC & EP Iter 1 & EP Iter 2 & EP Iter 3\\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi)$ & 200 & 0 & 200.07 & 200.05 & 200.21 & 200.02 \\
$Var(\phi)$ & -- & 20 & 2.03 & 1.89 & 1.98 & 1.58 \\
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

\begin{table}[ht]
\caption{Posterior of $\phi$ (K = 25)}
\centering
\begin{tabular}{c c c c c c c}
\hline
Parameter & True & Prior & HMC & EP Iter 1 & EP Iter 2 & EP Iter 3\\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi)$ & 200 & 0 & 200.07 & 200.27 & 200.15 & 199.98\\
$Var(\phi)$ & -- & 20 & 2.03 & 2.01 & 2.55 & 2.08\\
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

\pagebreak
\section{3. Uknown Means ( + Hierarchical Mean and Variance)}
\subsection{Formulation}
We then try a model with local unknown means drawn from a global unknown mean and unknown variance:
$$ \theta_j \sim N(\phi_1, e^{\phi_2})$$
$$ x_{ij} \sim N(\theta_j, 1) $$

Generating 50 $\theta_j$'s from $\phi_1 = 200$ and $e^{\phi_2} = 5$, and then sampling 1000 data points from each group $j$, we give EP and HMC the following priors:
$$ \left[ \begin{array}{c} \phi_1 \\ \phi_2 \end{array} \right] 
\sim N\biggl( \left[ \begin{array}{c} 0 \\ 0 \end{array} \right], 
\left[ \begin{array}{cc} 1000 & 0 \\ 0 & 1 \end{array} \right] \biggr)$$

\subsection{Results}
EP and HMC converge to same posterior of $\phi$ for a small number of sites. When using 25 sites, however, the center for the hierarchical mean is pulled too much towards the prior. This is surprising given that the Stan calls during this EP run are doing a great job of discovering the local means, just not the hierarchical mean. Overall, this suggests that stronger priors for the hierarchical parameters are needed when the number of sites is large.

\begin{table}[ht]
\caption{Posterior of $\phi$}
\centering
\begin{tabular}{c c c c c c c }
\hline
Parameter & True & Prior & HMC & EP K=5 & EP K=10 & EP K=25 \\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi_1)$ & 200 & 200 & 200.52 & 199.89 & 199.33 & 18.32 \\
$SD(\phi_1)$ & -- & 100 & 0.64 & 0.56 & 0.52 & NA \\
$E(\phi_2)$ & 1.61 & 0 & 1.51 & 1.50 & 1.45 & 5.13 \\
$SD(\phi_2)$ & -- & 1 & 0.10 & 0.10 & 0.11 & NA \\
$Cov(\phi_1,\phi_2)$ & -- & 0 & -0.0041 & -0.0088 & -0.0131 & 0.92 \\ \hline
Time (Serial) & -- & -- & 1137 s & 452 s & 467 s & 296 s\\ 
Time (Parallel) & -- & -- & 1137 s & 90.4 s & 46.7 s & 11.8 s\\
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

Fortunately, as in the previous model, we find that the posterior stabilizes after the first iteration. 

\begin{table}[ht]
\caption{Posterior of $\phi$ (K = 10)}
\centering
\begin{tabular}{c c c c c c c}
\hline
Parameter & True & Prior & HMC & EP Iter 1 & EP Iter 2 & EP Iter 3\\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi)$ & 200 & 0 & 200.52 & 199.33 & 200.87 & 200.62 \\
$SD(\phi)$ & -- & 100 & 0.64 & 0.52 & 0.77 & 0.64 \\
$E(\phi_2)$ & 1.61 & 0 & 1.51 & 1.45 & 1.48 & 1.50 \\
$SD(\phi_2)$ & -- & 1 & 0.10 & 0.11 & 0.10 & 0.09 \\
$Cov(\phi_1,\phi_2)$ & -- & 0 & -0.0041 & -0.0131 & -0.0335 & 0.0145 \\
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

\pagebreak
\section{4. Hierarchical Linear Model}
\subsection{Formulation}
Now we try a hierarchical linear model with local unknown slopes and intercepts drawn from global unknown slope/intercept mean and variance, as well as a global model variance:
$$ \alpha_j \sim N(\phi_1, e^{\phi_4}) \hspace{20 pt} \beta_j \sim N(\phi_2, e^{\phi_5}) \hspace{20 pt} \sigma_j \sim N(\phi_3, e^{\phi_6})$$
$$ x_{ij} \sim U(0,50) \hspace{20 pt} \epsilon_{ij} \sim N(0,1)$$
$$ y_{ij} = \alpha_j + \beta_j x_{ij} + \sigma_j \epsilon_{ij} $$

Generating 50 $\alpha_j$, $\beta_j$, and $\sigma_j$'s from $\phi = \{100, 20, \log 20, \log 1, \log 1.5, \log 0.5\}$, we then sampled 100 data points from each group $j$.

\subsection{Results}
EP and HMC converge to same posterior of $\phi$ for a small number of sites. 

\begin{table}[ht]
\caption{Posterior of $\phi$}
\centering
\begin{tabular}{c c c c c c c }
\hline
Parameter & True & Prior & HMC & EP K=5 & EP K=10 \\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi_1)$ & 100 & 0 & 100.3 & 100.3 & 100.3 \\
$SD(\phi_1)$ & -- & 31.6 & 0.51 & 0.53 & 0.52 \\ \hline
$E(\phi_2)$ & 20 & 0 & 19.8 & 19.8 & 19.76 \\
$SD(\phi_2)$ & -- & 31.6 & 0.19 & 0.20 & 0.21 \\ \hline
$E(\phi_3)$ & 3 & 0 & 3.01 & 2.98 & 3.01 \\
$SD(\phi_3)$ & -- & 1.41 & 0.07 & 0.08 & 0.10 \\ \hline
$E(\phi_4)$ & 0 & 0 & -0.03 & -0.025 & -0.24 \\
$SD(\phi_4)$ & -- & 0.71 & 0.54 & 0.45 & 0.46 \\ \hline
$E(\phi_5)$ & 0.41 & 0 & 0.27 & 0.32 & 0.39 \\
$SD(\phi_5)$ & -- & 0.71 & 0.10 & 0.11 & 0.11 \\ \hline
$E(\phi_6)$ & -0.69 & 0 & -0.59 & -0.61 & -0.65 \\
$SD(\phi_6)$ & -- & 0.71 & 0.11 & 0.12 & 0.14 \\ \hline
Time (Serial) & -- & -- & 535 s & 680 s & 680 s \\ 
Time (Parallel) & -- & -- & 535 s & 136 s & 68 s \\ 
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

\pagebreak
\section{5. Hierarchical Inverse Logistic Model}
\subsection{Formulation}
We next try a hierarchical inverse logistic model with five local unknown parameters drawn from global unknown means and variances:
$$ a_{pj} \sim N(\phi_p, e^{\phi_{p+5}}) \hspace{10 pt} 
\sigma_j = e^{a_{5j}}$$
$$ x_{ij} \sim U(0,50) \hspace{10 pt} \epsilon_{ij} \sim N(0, 1)$$
$$ y_{ij} = a_{1j} + \text{logit}^{-1} \biggl(\frac{x_{ij} - a_{2j}}{a_{3j}}\biggr) \cdot a_{4j} + \sigma_j \epsilon_{ij} $$

Generating 50 groups of $a_{pj}$ and $\sigma_j$'s from a $\phi$ drawn from the prior shown below, we then sampled 100 data points from each group $j$.

\subsection{Results}
EP and HMC converge to same posterior of $\phi$ for a small number of sites. When using 25 sites, however, the posterior variance is quite larger.

\begin{table}[ht]
\caption{Posterior of $\phi$}
\centering
\begin{tabular}{c c c c c c }
\hline
Parameter & True & Prior & HMC & EP K=5 & EP K=10 \\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi_1)$ & 395 & 361 & 391 & 359 & 5.73 \\
$SD(\phi_1)$ & -- & 22.4 & 8.65 & 2.69 & 0.118 \\ \hline
$E(\phi_2)$ & 9.20 & 10 & 8.99 & 11.1 & 1.19 \\
$SD(\phi_2)$ & -- & 3.16 & 0.87 & 0.62 & 0.121 \\ \hline
$E(\phi_3)$ & 2.22 & 2 & 2.17 & 1.96 & 0.96 \\
$SD(\phi_3)$ & -- & 0.32 & 0.18 & 0.14 & 0.105 \\ \hline
$E(\phi_4)$ & 664 & 650 & 656 & 652 & 6.65 \\
$SD(\phi_4)$ & -- & 22.4 & 18.7 & 3.32 & 0.108 \\ \hline
$E(\phi_5)$ & 2.10 & 2.08 & 1.97 & 2.22 & 1.44 \\
$SD(\phi_5)$ & -- & 0.71 & 0.13 & 0.16 & 0.101 \\ \hline
Time (Serial) & -- & -- & 1436 s & 100 s & 1350 s \\ 
Time (Parallel) & -- & -- & 1436 s & 20 s & 135 s \\ 
\hline
\end{tabular}
\label{table:nonlin}
\end{table}


\pagebreak
\section{8. Exponential Model}
\subsection{Formulation}
Finally we try the hierarchical exponential model with eight local unknown parameters drawn from global unknown means and variances, as well as a global model variance:
$$ \theta_p = \phi_p \hspace{30 pt} \tau_p = e^{\phi_{p+8}} \hspace{30 pt} \sigma = e^{\phi_{17}}$$
$$ \log a_{pj} \sim N(\theta_p, \tau_p)$$
$$ x_{ij} \sim U(0,50)$$
$$ \epsilon_{ij} \sim N(0, \sigma)$$
$$ y_{ij} = a_{1j} + \text{logit}^{-1} \biggl(\frac{x_{ij} - a_{2j}}{a_{3j}}\biggr) \biggl( a_{4j} \cdot a_{5j} \cdot \biggl(1 - e^{-\frac{x_{ij}}{a_{5j}}} \biggr) - a_{6j} \cdot e^{-\frac{1}{2}\biggl(\frac{x_{ij} - a_{7j}}{a_{8j}}\biggr)^2} \biggr) + \epsilon_{ij} $$

Generating 50 groups of $a_{pj}$'s from $\phi_{1:8} = \{ 5.89, 1.31, 0.77, 6.47, 1.69, -0.68, 3.9, 1.95\}$, $\phi_{9:16} = \{-1.07, -0.63, -0.25, -0.60, -0.69, -1.49, -1.24, -1.83\}$, and $\phi_{17} = 5.3$, we then sampled 100 data points from each group $j$.

\subsection{Results}
EP and HMC converge to same posterior of $\phi$ for a small number of sites. When using 25 sites, however, the posterior variance is quite larger.

\begin{table}[ht]
\caption{Posterior of $\phi$}
\centering
\begin{tabular}{c c c c c c c }
\hline
Parameter & True & Prior & HMC & EP K=5 & EP K=10 & EP K=25 \\ [0.5ex] % inserts table %heading
\hline \\
$E(\phi_1)$ & 5.89 & 5.89 & 6.05 & 5.67 & 5.73 & 5.53 \\
$SD(\phi_1)$ & -- & 0.71 & 0.13 & 0.102 & 0.118 & 0.122 \\ \hline
$E(\phi_2)$ & 1.31 & 1.31 & 1.50 & 1.20 & 1.19 & 1.20 \\
$SD(\phi_2)$ & -- & 0.71 & 0.17 & 0.123 & 0.121 & 0.098 \\ \hline
$E(\phi_3)$ & 0.77 & 0.77 & 0.69 & 0.74 & 0.96 & 0.98 \\
$SD(\phi_3)$ & -- & 0.71 & 0.18 & 0.097 & 0.105 & 0.095 \\ \hline
$E(\phi_4)$ & 6.47 & 6.47 & 7.37 & 6.81 & 6.65 & 6.75 \\
$SD(\phi_4)$ & -- & 0.71 & 0.18 & 0.105 & 0.108 & 0.095 \\ \hline
$E(\phi_5)$ & 1.69 & 1.69 & 0.72 & 1.44 & 1.44 & 1.57 \\
$SD(\phi_5)$ & -- & 0.71 & 0.19 & 0.10 & 0.101 & 0.094 \\ \hline
$E(\phi_6)$ & -0.68 & -0.68 & -1.21 & -1.00 & -0.56 & -0.92 \\
$SD(\phi_6)$ & -- & 0.71 & 0.41 & 0.095 & 0.066 & 0.15 \\ \hline
$E(\phi_7)$ & 3.90 & 3.90 & 1.76 & 4.01 & 3.93 & 3.93 \\
$SD(\phi_7)$ & -- & 0.71 & 0.99 & 0.060 & 0.088 & 0.105 \\ \hline
$E(\phi_8)$ & 1.95 & 1.95 & 1.34 & 2.05 & 2.22 & 1.95 \\
$SD(\phi_8)$ & -- & 0.71 & 0.40 & 0.083 & 0.136 & 0.179 \\ \hline
Time (Serial) & -- & -- & 908 s & 1300 s & 1350 s & 1170 s\\ 
Time (Parallel) & -- & -- & 908 s & 260 s & 135 s & 47 s\\ 
\hline
\end{tabular}
\label{table:nonlin}
\end{table}

