from matplotlib import rc
rc("font", family="serif", size=12)
rc("text", usetex=True)
rc("./weaklensing.tex")

import daft

pgm = daft.PGM([4.7, 3.15], origin=[-1.35, 2.2])
pgm.add_node(daft.Node("mu0", r"$\mu_0$", 0, 5))
pgm.add_node(daft.Node("tau0", r"$\tau_0^2$", -1, 4))
pgm.add_node(daft.Node("gamma0", r"$\gamma_{0i}$", 0, 4))
pgm.add_node(daft.Node("obs", r"$y_{ij}$", 1, 4, observed=True))
pgm.add_node(daft.Node("mu1", r"$\mu_1$", 2, 5))
pgm.add_node(daft.Node("tau1", r"$\tau_1^2$", 3, 4))
pgm.add_node(daft.Node("gamma1", r"$\gamma_{1i}$", 2, 4))
pgm.add_node(daft.Node("sigma", r"$\sigma_i^2$", 2, 3))
pgm.add_node(daft.Node("Sigma", r"$\Sigma$", 3, 3))
pgm.add_node(daft.Node("x", r"$x_{ij}$", 1, 3, observed=True))
pgm.add_plate(daft.Plate([0.5, 2.65, 1, 1.75],
                         label=r"$j$"))
pgm.add_plate(daft.Plate([-0.5, 2.25, 3, 2.25],
                         label=r"Longitude $i$"))
pgm.add_edge("mu0", "gamma0")
pgm.add_edge("tau0", "gamma0")
pgm.add_edge("gamma0", "obs")
pgm.add_edge("mu1", "gamma1")
pgm.add_edge("tau1", "gamma1")
pgm.add_edge("gamma1", "obs")
pgm.add_edge("x", "obs")
pgm.add_edge("Sigma", "sigma")
pgm.add_edge("sigma", "obs")
pgm.render()
pgm.figure.savefig("Linear_Model.png",dpi=1000)

pgm = daft.PGM([4.7, 3.15], origin=[-1.35, 2.2])
pgm.add_node(daft.Node("alpha0", r"$\alpha_0$", 0, 5))
pgm.add_node(daft.Node("beta0", r"$\beta_0$", -1, 4))
pgm.add_node(daft.Node("gamma0", r"$\gamma_{0i}$", 0, 4))
pgm.add_node(daft.Node("obs", r"$y_{ij}$", 1, 4, observed=True))
pgm.add_node(daft.Node("alpha1", r"$\alpha_1$", 2, 5))
pgm.add_node(daft.Node("beta1", r"$\beta_1$", 3, 4))
pgm.add_node(daft.Node("gamma1", r"$\gamma_{1i}$", 2, 4))
pgm.add_node(daft.Node("sigma", r"$\sigma_i^2$", 2, 3))
pgm.add_node(daft.Node("Sigma", r"$\Sigma$", 3, 3))
pgm.add_node(daft.Node("x", r"$x_{ij}$", 1, 3, observed=True))
pgm.add_plate(daft.Plate([0.5, 2.65, 1, 1.75],
                         label=r"$j$"))
pgm.add_plate(daft.Plate([-0.5, 2.25, 3, 2.25],
                         label=r"Longitude $i$"))
pgm.add_edge("alpha0", "gamma0")
pgm.add_edge("beta0", "gamma0")
pgm.add_edge("gamma0", "obs")
pgm.add_edge("alpha1", "gamma1")
pgm.add_edge("beta1", "gamma1")
pgm.add_edge("gamma1", "obs")
pgm.add_edge("x", "obs")
pgm.add_edge("Sigma", "sigma")
pgm.add_edge("sigma", "obs")
pgm.render()
pgm.figure.savefig("SquareRoot_Model.png",dpi=1000)